<?php

namespace Dywee\NotificationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertRepository extends EntityRepository
{
    public function countNew($type = null)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('count(a)')
            ->where('a.isReaded = 0');

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function findForDropdown()
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->orderBy('a.createdAt', 'desc')
            ->where('a.isReaded = 0')
        ;

        return $qb->getQuery()->getResult();
    }
}
