<?php

namespace Dywee\NotificationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    public function countNew($type = null)
    {
        $qb = $this->createQueryBuilder('n')
            ->select('count(n)')
            ->where('n.isReaded = 0');

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function getForDropdown($user = null)
    {
        $qb = $this->createQueryBuilder('n')
            ->select('n')
            ->where('n.isReaded = 0')
            ->orderBy('n.createdAt', 'desc')
        ;

        if($user)
            $qb->andWhere('n.user = :user')->setParameter('user', $user);

        return $qb->getQuery()->getResult();
    }
}
